import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.3
blur = true

option_as_alt = "Both"


[font]
normal.family = "DankMono Nerd Font"

size = 22

