#!/bin/bash

# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

SKETCHY_DIR="$(pwd)"

SKETCHY_PLUGINS_DIR="$SKETCHY_DIR/plugins"
SKETCHY_ITEMS_DIR="$SKETCHY_DIR/items"

source "$SKETCHY_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
sketchybar --bar position=top \
                 sticky=off \
                 height=36 \
                 blur_radius=32 \
                 padding_left=8 \
                 padding_right=8 \
                 color=$SKETCHY_BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Semibold:15.0"
  icon.color="$SKETCHY_WHITE"
  label.font="SF Pro:Semibold:15.0"
  label.color="$SKETCHY_WHITE"
  background.color="$SKETCHY_ITEM_BG_COLOR"
  background.corner_radius=5
  background.height=24
  padding_left=4
  padding_right=4
  label.padding_left=4
  label.padding_right=8
  icon.padding_left=8
  icon.padding_right=4
)
sketchybar --default "${default[@]}"

# --- Righ Side Items ----
source "$SKETCHY_ITEMS_DIR/calendar.sh"
source "$SKETCHY_ITEMS_DIR/volume.sh"


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
