setup:
	@echo "📣 check about Deploy a First Release"
	@echo ">> heck about https://www.youtube.com/watch?v=hWGgalXZ3TA"
	@npm i -g commitizen cz-adapter-ruby
	@echo '{ "path": "cz-adapter-ruby" }' > $(DOTFILES_PATH)/workflow/.czrc
	@ln $(DOTFILES_PATH)/workflow/.czrc $(HOME)/.czrc
